APP_VERSION=1.1.1
APP_RELEASE=beta-0

LIST_IPSET_TTL=86400

DNS_DEFAULT=127.0.0.1#9753
# Upstream for dnsmasq (stubby DoT)
DNS_UPSTREAM=127.0.0.1#5353
DNS_STATIC_1=9.9.9.9
DNS_STATIC_2=8.8.8.8

DNSMASQ_LISTEN_IP=
DNSMASQ_PORT=9753
DNSMASQ_SWAP_PORT=6953

SSR_DNS_PORT=1181

STUBBY_PORT=5353

GW_DEFAULT=
MASK_DEFAULT=
ETH_DEFAULT=
EXTERNAL_IP=

INFACE_CLI=
INFACE_ENT=
INFACE_GUEST_ENT=

SETUP_FINISHED=
