#!/bin/sh
#------------------------------------------------------------------------------
#
#       Forest Router Tool (FRT)
#
#------------------------------------------------------------------------------
#
#       Правила пропуска DNS трафика по порту 53 (tcp/udp) при VPN/Shadowsocks.
#       https://github.com/ndmsystems/packages/wiki/Opkg-Component
#
# ------------------------------------------------------------------------------
#       Лицензия: Apache License 2.0
# ------------------------------------------------------------------------------

if [ "${type}" = 'iptables' ] && [ "${table}" = 'nat' ] ; then
	. /opt/apps/frt/bin/libs/ndm

	ip4__dns__add_routing_for_home &> /dev/null
fi
