#!/bin/sh

. /opt/apps/frt/bin/libs/ndm_d

if [ "${1}" = "hook" ] && [ "${change}" = "link" ] ; then

	 if echo "${id}" | grep -qE 'PPTP|L2TP' && is_cli_iface_global "${id}"; then
		tmp_file=/opt/tmp/sub_connection

		case "${connected}-${link}-${up}" in
			"no-down-down" )
				touch "${tmp_file}"
			;;
			"yes-up-up" )
				[ -f "${tmp_file}" ] && {
					cmd_vpn_iptable_reset &> /dev/null
					logger -t "FRT"  "Соединение ${id} успешно подключено, правила восстановлены!"
					rm -f "${tmp_file}"
				}
			;;
		esac
	fi

	if [ "${id}" = "$(inface_cli)" ]; then
		case "${connected}-${link}-${up}" in
			"no-down-down" )
				cmd_vpn_iptable_reset &> /dev/null
				logger -t "FRT"  "Соединение ${id} прервано. Правила и таблицы очищены."
			;;
			"yes-up-up" )
				link_reboot &> /dev/null
				logger -t "FRT"  "Соединение ${id} установлено. Правила и таблицы пересозданы."
			;;
		esac
	fi
fi
